# remotes::install_github("stan-dev/posteriordb-r")
library(posteriordb)
pdbl <- pdb_local("posterior_database")
print(Sys.getenv("steps.files.outputs.all"))
print(Sys.getenv("changed_file"))
print(Sys.getenv("all"))
print(readLines("added_modified.txt"))
#status_code <- check_pdb(pdbl, run_stan_code_checks = FALSE)
status_code <- 0L
q(status = status_code)
