# remotes::install_github("stan-dev/posteriordb-r")
library(posteriordb)
pdbl <- pdb_local("posterior_database")
print(Sys.getenv("steps.files.outputs.added_modified"))
status_code <- check_pdb(pdbl, run_stan_code_checks = FALSE)
q(status = status_code)
